In [89]:
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf


In [90]:
tf.__version__

'2.18.0'

In [91]:
#Importing the dataset
dataset=pd.read_csv("./Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [92]:
#print(dataset)

In [93]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [94]:
print(y)

[1 0 1 ... 1 1 0]


In [95]:
##ENCODING CATEGORICAL DATA

#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [96]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [97]:
#One hot encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [98]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [99]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [100]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [101]:
##BUILDING THE ANN

#Initializing the ANN
ann= tf.keras.models.Sequential()

In [102]:
#Adding the input layer and thefirst hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [103]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [104]:
#Adding the outpuy layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [105]:
##TRAINING THE ANN

#Compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])


In [106]:
#Training the ANN on the training set
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7945 - loss: 0.5686
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7928 - loss: 0.4750
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7991 - loss: 0.4448
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.8030 - loss: 0.4208
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.8000 - loss: 0.4100
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.7962 - loss: 0.4036
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7944 - loss: 0.3933
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.8367 - loss: 0.3838
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8386 - loss: 0.3843
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8462 - loss: 0.3661  
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.8430 - loss: 0.3705
Epoch 12/100
250/25

In [114]:
##MAKING THE PREDICTIONS AND EVALUATING THE MODEL
#Predicting the result of a single observation

"""HOMEWORK

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?"""

#Solution
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[False]]


In [115]:
#Predicting the test set result
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [116]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1505   90]
 [ 191  214]]


0.8595